---
title: homes.co.nz
timezone: Pacific/Auckland
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  test:
    title: Test
    output: true
  uploads:
    title: Uploads
    output: true
email: greg.day@homes.co.nz
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: greg.day@homes.co.nz
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
sass:
  style: compressed
  load_paths:
    - bower_components/bootstrap-sass/assets/stylesheets
    - _sass
