---
title: homes.co.nz
timezone: Pacific/Auckland
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  test:
    title: Test
    output: true
  uploads:
    title: Uploads
    output: true
email: greg.day@homes.co.nz
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: greg.day@homes.co.nz
github_username: jekyll
markdown: kramdown
theme: minima 
plugins:
- jekyll-feed

sass:
  # loading path from site root
  # default to _sass
  #sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed
  load_paths:
      - _sass
      - bower_components/bootstrap-sass/assets/stylesheets
